# Generated by Django 5.2.5 on 2025-11-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0006_delete_booking_delete_meetingroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_cheques', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='offices.office')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due for Deposit'), ('Deposited', 'Deposited'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced')], default='Pending', max_length=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='accounting.lease')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
