# Generated by Django 6.0.1 on 2026-01-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('offices', '0006_delete_booking_delete_meetingroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='offices.office'),
        ),
    ]
