# Generated by Django 6.0.1 on 2026-01-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_lease_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
