# Generated by Django 5.2.5 on 2025-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('size_sqft', models.DecimalField(decimal_places=2, max_digits=7)),
                ('annual_rent', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=10)),
            ],
        ),
    ]
