# Generated by Django 5.2.5 on 2025-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_populate_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='The date the current lease expires.', null=True),
        ),
    ]
