# Generated by Django 5.2.5 on 2025-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_office_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
