# Generated by Django 5.2.5 on 2025-09-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_meetingroom_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
    ]
