# Generated by Django 5.2.5 on 2025-09-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('offices', '0006_delete_booking_delete_meetingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='associated_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_room_bookings', to='offices.office'),
        ),
    ]
